LANG_NAMES={"fa":"فارسی","en":"English","ar":"العربية","zh":"中文"}
LABELS={
"fa":{"report":"گزارش جامع متره ساختمان بتنی","project":"پروژه","members":"تعداد اعضا","concrete":"حجم کل بتن (m³)","rebar_exec":"وزن اجرای میلگرد (kg)","stock":"تعداد شاخه خرید","rebar_buy":"وزن خرید میلگرد (kg)","detail":"متره تفصیلی","section":"بخش","member":"عضو","item":"آیتم","quantity":"مقدار","unit":"واحد","notes":"توضیحات","rebar_type":"نوع میلگرد","dia":"قطر","pieces":"تعداد قطعه","exec_len":"طول اجرا (m)","exec_weight":"وزن اجرا (kg)","stock_bars":"شاخه خرید","buy_len":"طول خرید (m)","buy_weight":"وزن خرید (kg)","procurement":"خرید میلگرد بر اساس قطر","qa":"کنترل کیفی","status":"وضعیت","ok":"موردی یافت نشد","warning":"هشدار","cut":"لیست برش","used":"طول مصرفی (m)","waste":"پرت برش (m)","unit_totals":"جمع واحدها","ai":"یادداشت هوشمند","final_note":"مقادیر بر اساس اطلاعات نقشه محاسبه شده و باید با نقشه‌ها و مدارک مصوب پروژه کنترل شوند.","check":"نیازمند بررسی","standard":"استاندارد","language":"زبان","stock_length":"طول شاخه استاندارد"},
"en":{"report":"STRUCTURAL TAKEOFF REPORT","project":"Project","members":"Member Count","concrete":"Total Concrete (m³)","rebar_exec":"Execution Rebar Weight (kg)","stock":"Stock Bars","rebar_buy":"Procurement Rebar Weight (kg)","detail":"Detailed Takeoff","section":"Section","member":"Member","item":"Item","quantity":"Quantity","unit":"Unit","notes":"Notes","rebar_type":"Rebar Type","dia":"Dia.","pieces":"Pieces","exec_len":"Exec. Length (m)","exec_weight":"Exec. Weight (kg)","stock_bars":"Stock Bars","buy_len":"Buy Length (m)","buy_weight":"Buy Weight (kg)","procurement":"Rebar Procurement by Diameter","qa":"QA REVIEW","status":"Status","ok":"OK","warning":"WARNING","cut":"Cut List","used":"Used Length (m)","waste":"Cut Waste (m)","unit_totals":"Unit Totals","ai":"AI Notes","final_note":"Quantities are based on drawing inputs and must be checked against approved project documents.","check":"CHECK REQUIRED","standard":"Standard","language":"Language","stock_length":"Stock Length"},
"ar":{"report":"تقرير حصر كميات المنشأ الخرساني","project":"المشروع","members":"عدد العناصر","concrete":"إجمالي الخرسانة (م³)","rebar_exec":"وزن حديد التسليح التنفيذي (كغ)","stock":"عدد القضبان القياسية","rebar_buy":"وزن حديد التسليح للشراء (كغ)","detail":"الحصر التفصيلي","section":"القسم","member":"العنصر","item":"البند","quantity":"الكمية","unit":"الوحدة","notes":"الملاحظات","rebar_type":"نوع حديد التسليح","dia":"القطر","pieces":"عدد القطع","exec_len":"طول التنفيذ (م)","exec_weight":"وزن التنفيذ (كغ)","stock_bars":"قضبان الشراء","buy_len":"طول الشراء (م)","buy_weight":"وزن الشراء (كغ)","procurement":"شراء حديد التسليح حسب القطر","qa":"مراجعة الجودة","status":"الحالة","ok":"لا توجد ملاحظات","warning":"تحذير","cut":"قائمة القطع","used":"الطول المستخدم (م)","waste":"هدر القطع (م)","unit_totals":"إجمالي الوحدات","ai":"ملاحظات ذكية","final_note":"تم حساب الكميات بناءً على بيانات المخططات ويجب مطابقتها مع مستندات المشروع المعتمدة.","check":"يتطلب المراجعة","standard":"المعيار","language":"اللغة","stock_length":"طول القضيب القياسي"},
"zh":{"report":"混凝土结构工程量统计报告","project":"项目","members":"构件数量","concrete":"混凝土总量 (m³)","rebar_exec":"钢筋施工重量 (kg)","stock":"标准钢筋根数","rebar_buy":"钢筋采购重量 (kg)","detail":"详细工程量","section":"分部","member":"构件","item":"项目","quantity":"数量","unit":"单位","notes":"说明","rebar_type":"钢筋类型","dia":"直径","pieces":"构件数量","exec_len":"施工长度 (m)","exec_weight":"施工重量 (kg)","stock_bars":"采购根数","buy_len":"采购长度 (m)","buy_weight":"采购重量 (kg)","procurement":"按直径统计钢筋采购","qa":"质量检查","status":"状态","ok":"无警告","warning":"警告","cut":"下料清单","used":"使用长度 (m)","waste":"下料损耗 (m)","unit_totals":"单位汇总","ai":"智能说明","final_note":"工程量依据图纸输入计算，必须与经批准的项目文件进行核对。","check":"需要检查","standard":"标准","language":"语言","stock_length":"标准钢筋长度"}}
}
ITEMS={
"en":{"فونداسیون":"Foundation","ستون":"Column","تیر":"Beam","سقف":"Slab/Roof","دیوار":"Wall","پله":"Stair","آرماتور":"Reinforcement","بتن":"Concrete","میلگرد":"Rebar","میلگرد طولی":"Longitudinal Reinforcement","میلگرد عرضی":"Transverse Reinforcement","میلگرد انتظار ستون":"Column Starter Bars","انتظار راه‌پله":"Stair Starter Bars","چاله آسانسور":"Elevator Pit","میلگرد تقویتی":"Additional Reinforcement","میلگرد پایینی تیر":"Beam Bottom Reinforcement","میلگرد بالایی تیر":"Beam Top Reinforcement","خاموت":"Stirrups","میلگرد منفی":"Negative Reinforcement","اتکا/ادکا":"Support Bars","مساحت":"Area","حجم":"Volume","تعداد":"Count","طول":"Length","عرض":"Width","ضخامت":"Thickness"},
"ar":{"فونداسیون":"الأساسات","ستون":"الأعمدة","تیر":"الكمرات","سقف":"البلاطة/السقف","دیوار":"الجدار","پله":"الدرج","آرماتور":"التسليح","بتن":"الخرسانة","میلگرد":"حديد التسليح","میلگرد طولی":"التسليح الطولي","میلگرد عرضی":"التسليح العرضي","میلگرد انتظار ستون":"أشاير الأعمدة","انتظار راه‌پله":"أشاير الدرج","چاله آسانسور":"حفرة المصعد","میلگرد تقویتی":"تسليح إضافي","میلگرد پایینی تیر":"تسليح سفلي للكمرات","میلگرد بالایی تیر":"تسليح علوي للكمرات","خاموت":"كانات","میلگرد منفی":"تسليح سالب","اتکا/ادکا":"تسليح الدعم","مساحت":"المساحة","حجم":"الحجم","تعداد":"العدد","طول":"الطول","عرض":"العرض","ضخامت":"السماكة"},
"zh":{"فونداسیون":"基础","ستون":"柱","تیر":"梁","سقف":"楼板/屋面","دیوار":"墙","پله":"楼梯","آرماتور":"钢筋","بتن":"混凝土","میلگرد":"钢筋","میلگرد طولی":"纵向钢筋","میلگرد عرضی":"横向钢筋","میلگرد انتظار ستون":"柱插筋","انتظار راه‌پله":"楼梯插筋","چاله آسانسور":"电梯井坑","میلگرد تقویتی":"附加钢筋","میلگرد پایینی تیر":"梁底部钢筋","میلگرد بالایی تیر":"梁顶部钢筋","خاموت":"箍筋","میلگرد منفی":"负筋","اتکا/ادکا":"支撑筋","مساحت":"面积","حجم":"体积","تعداد":"数量","طول":"长度","عرض":"宽度","ضخامت":"厚度"}}
def lang_code(lang): return lang if lang in LABELS else "fa"
def L(key,lang="fa"): return LABELS[lang_code(lang)].get(key,key)
def item_label(text,lang="fa"):
    s=str(text or "")
    if lang_code(lang)=="fa": return s
    for src,dst in sorted(ITEMS.get(lang_code(lang),{}).items(),key=lambda x:-len(x[0])): s=s.replace(src,dst)
    return s
